"""Dump human-readable per-capability verb/role docs.

Walks every capability class in `project_management_crud_example.capabilities`
and emits its class docstring to a single Markdown file at
`backend/evidence/capabilities/verbs.md`. Routes / dashboards / reviewers can
diff this artifact to see which verbs each capability advertises and which
roles can call them.

POC mechanism: read class docstrings verbatim. Drift between docstring and the
actual role-set constants is possible — a future iteration replaces this with
mechanical extraction from a `_VERBS` mapping on each class.

Usage (from backend/):
    python -m project_management_crud_example.tools.dump_capabilities_doc
"""

from __future__ import annotations

import inspect
import sys
from pathlib import Path
from typing import List

from project_management_crud_example import capabilities as caps_module


def _capability_classes() -> List[type]:
    """Return every class exported by `capabilities.__all__` whose name ends in `Capability`."""
    classes: List[type] = []
    for name in caps_module.__all__:
        member = getattr(caps_module, name, None)
        if inspect.isclass(member) and name.endswith("Capability"):
            classes.append(member)
    classes.sort(key=lambda c: (c.__module__, c.__name__))
    return classes


def _render(classes: List[type]) -> str:
    lines: List[str] = []
    lines.append("# Capability verbs and roles")
    lines.append("")
    lines.append(
        "Generated by `python -m project_management_crud_example.tools.dump_capabilities_doc`. "
        "Do not edit by hand — re-run the script."
    )
    lines.append("")
    for cls in classes:
        lines.append(f"## `{cls.__name__}`")
        lines.append("")
        lines.append(f"_module: `{cls.__module__}`_")
        lines.append("")
        doc = inspect.getdoc(cls) or "_(no docstring)_"
        lines.append(doc)
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    classes = _capability_classes()
    output_path = Path(__file__).resolve().parents[2] / "evidence" / "capabilities" / "verbs.md"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(_render(classes), encoding="utf-8")
    print(f"Wrote {output_path} ({len(classes)} classes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
